# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 第二天堂                      #博客名
subtitle: 简单的生活，更少的期待，更多的付出。     #博客副标题
description: 生活啊，就像我的歌声，时而不靠谱，时而不着调。但总会打动自己              #网站描述
keywords: 颜哲,yanzhe,yzhe           #用于爬虫抓取的关键词
author: 颜哲                         #作者名称
email: yanzhe919@gmail.com           #作者邮箱
language: zh-CN                   #zh-Hans        #网页编码,中文
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.yanzhe.tk    #用于绑定域名, 其他的不需要配置
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
    #- README.md

# Writing   设置生成博文的默认格式,不修改
new_post_name: :year-:month-:day-:title.md # File name of new posts  #:year-:month-:day-:title.md
default_layout: post
auto_spacing: true	#在中文和英文之间加入空格
titlecase: false # Transform title into titlecase
external_link:
  enable: false # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1	#把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false	#显示草稿
post_asset_folder: true	#启动 Asset 文件夹
relative_link: false	#把链接改为与根目录的相对位址
future: true	#	显示未来的文章
highlight:	#代码块的设置
  enable: true
  line_number: true
  auto_detect: true	#自动检测语言类型
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 20

# Category & Tag
default_category: uncategorized	#默认分类
category_map:			#分类别名
tag_map:				#标签别名

# Date / Time format	日期格式   wo-DDDo
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD  dddd
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination   分页, 设置每页显示多少篇博文
## Set per_page to 0 to disable pagination
per_page: 10	#每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page	#分页目录

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

sitemap:
    path: sitemap.xml
#    template: ./sitemap_template.xml
    rel: false

baidusitemap:
path: baidusitemap.xml

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next         #coney    #主题设置

# Likely Share
# See: https://ilyabirman.net/projects/likely/, https://github.com/ilyabirman/Likely
# Likely supports four looks, nine social networks, any button text.
# You are free to modify the text value and order of any network.
likely:
  enable: true
  cdn:
    js: //cdn.jsdelivr.net/npm/ilyabirman-likely@2/release/likely.min.js
    css: //cdn.jsdelivr.net/npm/ilyabirman-likely@2/release/likely.min.css
  look: normal    # available values: normal, light, small, big
  networks:
    twitter: Tweet
    facebook: Share
    linkedin: Link
    gplus: Plus
    vkontakte: VK
    odnoklassniki: Class
    telegram: Send
    whatsapp: Send
    pinterest: Pin

# NeedMoreShare2
# Dependencies: https://github.com/theme-next/theme-next-needmoreshare2
# For more information: https://github.com/revir/need-more-share2
# iconStyle: default | box
# boxForm: horizontal | vertical
# position: top / middle / bottom + Left / Center / Right
# networks:
# Weibo | Wechat | Douban | QQZone | Twitter | Facebook | Linkedin | Mailto | Reddit | Delicious | StumbleUpon | Pinterest
# GooglePlus | Tumblr | GoogleBookmarks | Newsvine | Evernote | Friendfeed | Vkontakte | Odnoklassniki | Mailru
needmoreshare:
  enable: true
  cdn:
    js: //cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@1/needsharebutton.min.js
    css: //cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@1/needsharebutton.min.css
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,QQZone,Evernote,Douban,Twitter,Facebook
  float:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,QQZone,Evernote,Douban,Twitter,Facebook

# share.js
# See: https://github.com/overtrue/share.js
# networks: weibo,qq,wechat,tencent,douban,qzone,linkedin,diandian,facebook,twitter,google
sharejs:
  enable: true
  cdn:
    js: //cdn.jsdelivr.net/npm/social-share.js@1/dist/js/social-share.min.js
    css: //cdn.jsdelivr.net/npm/social-share.js@1/dist/js/social-share.min.css
  networks: weibo,qq,wechat,tencent,douban,qzone,linkedin,diandian,facebook,twitter,google
  wechat_qrcode:
    title: 微信扫一扫：分享
    prompt: 微信里点“发现”，扫一下二维码便可将本文分享至朋友

# hexo-tag-cloud
tag_cloud:
    textFont: 'Trebuchet MS, Helvetica'
    textColor: '#333'
    textHeight: 25
    outlineColor: '#87CEEB'
    maxSpeed: 0.1 # range from [0.01 ~ 1]
    pauseOnSelected: false # true means pause the cloud tag movement when highlight a tag

#all_minifier
#all_minifier: true
js_concator:
 enable: false
 bundle_path: '/js/bundle.js'
 front: false
 silent: false

html_minifier:
 enable: true
 ignore_error: false
 silent: true
 exclude:
  #- '*.md'
  #- '*.swig'

css_minifier:
 enable: true
 silent: false
 exclude:
  - '*.min.css'
  - 'needsharebutton.css'

js_minifier:
 enable: true
 mangle: true
 silent: false
# output:
# compress:
 exclude:
  - '*.min.js'
  - 'tw_cn.js'
  - 'love.js'
  - 'lib/*.js'

image_minifier:
 enable: true
 interlaced: false
 multipass: false
 optimizationLevel: 2
 pngquant: false
 progressive: false
 silent: true

# hexo-filter-optimize 还不太好用，但是 hexo-all-minifier 会在alpine编译失败
filter_optimize:
  enable: false
  # remove the surrounding comments in each of the bundled files
  remove_comments: false
  css:
    # minify all css files
    minify: true
    # bundle loaded css file into the one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
      - '*.min.css'
      - 'needsharebutton.css'

  js:
    # minify all js files
    minify: true
    # bundle loaded js file into the one
    bundle: true
    excludes:
      - '*.min.js'
      - 'tw_cn.js'
      - 'love.js'
      - 'lib/*.js'
  # set the priority of this plugin,
  # lower means it will be executed first, default is 10
  priority: 12

##开启繁简体
translateLink: true

#开启google AdSense，google广告
google_adsense:
  enable: true
  google_ad_client: ca-pub-2525576362651538

#安装 hexo-generator-searchdb,自定义站点内容搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

#安装 hexo-symbols-count-time ，统计字数和预估阅读时间
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: false

#安装hexo-leancloud-counter-security，统计文章阅读次数
leancloud_counter_security:
  enable_sync: false
  #app_id: mG33GaRcAui3HLm8F5U0fbvs-MdYXbMMI
  #app_key: ognOYyodI46iflJOVx6VCsrR
  app_id: LKlB9WEblTuWsQlORotpASuM-gzGzoHsz
  app_key: oFb6ac842C0pIdBuW6t56Ezf
  username: <<your username>> # Will be asked while deploying if is left blank
  password: <<your password>> # Recommmended to be left blank. Will be asked while deploying if is left blank

# Change title and favicon when window is hidden and visible.
title_change:
  enable: true

  # Enabling this feature on non-desktop devices may not be a good choice, but it depends on you.
  onmobile: false

  # Enable random title or not.
  # Basically `random: true` means you have several titles to display and `random: false` means you have only one title to display.
  # When `random: true`, YOU MUST FOLLOW the format which has been commented in two title options below.
  # When `random: false`, please fill in the same line of the title option, like `title: one title`.
  random: false

  # Restore the original title after the specified time in milliseconds.
  timeout: 2019

  # Options when window is hidden.
  hidden:
    favicon: /images/favicon.ico
    title:
      #- 404
      - φ(*￣0￣)
      - Waiting for you.

  # Options when window is visible.
  visible:
    favicon: /images/favicon.ico
    title:
      #- 200
      - (✿◡‿◡)
      - Welcome back!

# Deployment
## Docs: https://hexo.io/docs/deployment.html
### Customize commit message (Default to Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }})
###$ hexo deploy -m "Commit message"
deploy:
 - type: git		#部署类型, 本文使用Git
   repo:
    github: git@github.com:yanzhe919/yanzhe919.github.io.git,master	#部署分支,一般使用master主分支
    gitee: git@gitee.com:yanzhe919/yanzhe919.git,master
    #coding: <repository url>,[branch]
   #extend_dirs:
   #  - [extend directory]
   #  - [another extend directory]
   #ignore_hidden:
   # public: false
   # [extend directory]: true
   # [another extend directory]: false
   #ignore_pattern:
   # [folder]: regexp  # or you could specify the ignore_pattern under a certain directory
 - type: git
   repo: git@github.com:yanzhe919/yanzhe919.github.io.git
   branch: hexo
   extend_dirs: /
   #exlude:
   #  - node_modules/
   #  - public/
   ignore_hidden: false
   ignore_pattern:
    public: .
    /: "node_modules|public"

