# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [hexo] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    name: Hexo deploy to GitHub Pages & Gitee Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      GIT_NAME: yanzhe919
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      REPO: github.com/yanzhe919/yanzhe919.github.io
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Get Latest Commit Message
      run: |
        git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        sed -i '18s/imageLink/imageLink.replace(\/\![0-9]{3,}x\/,"")/' themes/next/source/js/utils.js
        git clone https://$GH_TOKEN@$REPO public
        hexo g
    # hexo clean & hexo g

    - name: Deploy to Github Pages
      run: |
        cd ./public && git init && git add .
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master

    - name: Deploy to Gitee Pages
      env:
        ID_ED25519_GITEE: ${{ secrets.ID_ED25519_GITEE }}
        GITEE_REPO: gitee.com:yanzhe919/yanzhe919.git
      run: |
        cd ..
        mkdir -p ~/.ssh/
        echo "${ID_ED25519_GITEE}" > ~/.ssh/id_ed25519_gitee
        chmod 600 ~/.ssh/id_ed25519_gitee
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
        ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
        echo "Host gitee.com" >> ~/.ssh/config
        echo " HostName gitee.com" >> ~/.ssh/config
        echo " User yanzhe919" >> ~/.ssh/config
        echo " PreferredAuthentications publickey" >> ~/.ssh/config
        echo " IdentityFile ~/.ssh/id_ed25519_gitee" >> ~/.ssh/config
        git rm -rf --cached ./public
        git clone git@${GITEE_REPO} gitee_blog
        cd gitee_blog
        git checkout master
        cd ../
        \cp -rf ./public ./gitee_blog/
        cd gitee_blog
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "git@${GITEE_REPO}" master:master
