# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [hexo] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        sed -i '18s/imageLink/imageLink.replace(\/\![0-9]{3,}x\/,"")/' themes/next/source/js/utils.js
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: yanzhe919
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/yanzhe919/yanzhe919.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master
    # Gitee 推送方式不同，现在只开放了 OpenAPI 和 OAuth ，可参考 https://blog.csdn.net/z_johnny/article/details/104061608 实现
    # - name: Deploy to Gitee Pages
    #   env:
    #     GIT_NAME: yanzhe919
    #     GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    #     GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
    #     GITEE_REPO: gitee.com/yanzhe919/yanzhe919
    #   run: |
    #     git push --force --quiet "https://$GIT_NAME:$GITEE_TOKEN@$GITEE_REPO" master:master
